server.port=8080
server.servlet.context-path=/teneator

tenea.base.url=https://schaefer.tenea.com
tenea.app.path=GestionAccesos-3.2.4
tenea.login.path=/base/Login
tenea.login.return.url=/ControlAccesos/CreateEmployee
tenea.create.employee.path=/ControlAccesos/CreateEmployee
tenea.insert.register.path=/ControlAccesos/InsertRegisterAccess
tenea.update.register.path=/ControlAccesos/UpdateRegisterAccess
tenea.list.employee.path=/ControlAccesos/_ListEmployeenm_Partial
tenea.list.employee.referer=/ControlAccesos/ListEmployeenm
tenea.user.info.path=/Common/api/v4/Common/UserInfo
tenea.username=111222
tenea.password=XXXxxx
tenea.user.agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

# Session persistence
tenea.sessions.file.path=sessions.json
tenea.session.expiration.minutes=60

spring.application.name=TeneaAutomation
